<?php

$GLOBALS['REGISTRATIONS'] = array(
"anzeige"             => "Anzeige",
"algorythmus"         => "Algorythmus",
"aoe"                 => "Age of Empires",
"appsdreamer"			=> "Apps Dreamer",
"bullzbear"                 => "Bullzbear",
"blindc"					=> "Blind C",
"catechize"                 => "Catechize",
"codemutants"                 => "Code Mutants",
"collaborate"                 => "Collaborate",
"counterstrike"                 => "Counter-Strike",
"cozener"                 => "Cozener",
"crazyganith"                 => "Crazy Ganith",
"cynosure"					=> "Cynosure",
"dota"                 => "DOTA",
"dlounge"   		 => "D-Lounge",
"djnight"		=> "DJ Night",
"excogitate"                 => "Excogitate",
"felicity"                 => "Felicity",
"fifa"                      => "Fifa",
"footloose"                 => "Footloose",
"forage"                 => "Forage",
"googlockholmes"                 => "Googlock Holmes",
"gsaw"                        =>  "Game, Simulation and Animation workshop",
"headrush"                 => "Head Rush",
"hiphopstreet"             => "The Hip Hop Street",
"imagineer"                 => "Imagineer",
"instinct"                 => "Instinct",
"rivaldo"		=> "Nitin Gupta (Rivaldo)",
"mizmaze"                 => "Mizmaze",
"naach"                 => "Naach",
"naivete"                 => "Naivete",
"nfs"                 => "NFS",
"parley"                 => "Parley",
"proscenium"                 => "Proscenium",
"psd"                       => "PSD",
"quake3"                       => "Quake 3",
"rampage"                 => "Rampage",
"rhapsody"                 => "Rhapsody",
"ragnarock"					=> "Ragnarock",
"satbotrix"               => "Satbotrix",
"solution"                 => "Solution",
"synapshot"                 => "Synapshot",
"synapcity"					=> "Synapcity",
"techmarket"                 => "Tech Market",
"techimagine"                 => "Tech Imagine",
"pehchaan_kaun"                 => "Pehchaan Kaun?",
"shiamak_workshop"				=> "Shiamak Workshop",
"vista"                 => "Vista",
"webunleashed"                 => "Web Unleashed",
"rhythm_pulze"		=> "Rhythm Pulze",
);

?>
